//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailBill
    {
        public int number { get; set; }
        public int id_Bill { get; set; }
        public int id_F { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Food Food { get; set; }
    }
}
